# 第3章 PyTorchにおけるテンソルの扱い方

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
print(a[0])
a[2] = 3.0
print(a)

1.0
[1.0, 2.0, 3.0]


In [3]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

## 3.2 多次元配列としてのテンソル

In [7]:
a = [1.0, 2.0, 1.0]

In [8]:
a[0]

1.0

In [9]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

### 3.2.2 テンソルの作成

In [10]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [11]:
a[1]

tensor(1.)

In [12]:
float(a[1])

1.0

In [13]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 PyTorchテンソルの本質

In [15]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points.shape

torch.Size([3, 2])

In [23]:
points[0, 1]

tensor(1.)

In [24]:
points[0]

tensor([4., 1.])

## 3.3 テンソルの一部指定や取り出し(Indexing)

In [25]:
some_list = list(range(6))
some_list[:] # 全要素の指定
some_list[1:4] # 1から3まで
some_list[1:] # 1以降
some_list[:4] # 最初から3まで
some_list[:-1] # 最初から最後の1つ手前まで
some_list[1:4:2] # 1から3まで2つ置き

[1, 3]

In [26]:
points[1:] # 行1以降、列は全て
points[1:,:] # 行1を指定、陽に列も指定
points[1:, 0] # 行1以降で列0
points[None] # 新たな次元を追加。unsqeeezeと同じ働き

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 3.4 名前付きテンソル(Named Tensor)

In [28]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[-0.7326, -0.2765, -0.5855, -0.5682, -0.5043],
         [-0.6429,  0.7079, -2.0985, -1.2246, -1.2075],
         [ 2.2403, -0.2605, -0.3388,  0.4407,  0.0956],
         [ 0.2740, -0.5394,  0.0726,  0.0500, -0.1931],
         [ 1.5801, -1.6097, -1.5491, -0.3136, -0.1432]],

        [[-0.0124, -1.2427,  0.5558,  0.3259,  1.4868],
         [-0.4964, -1.0148, -1.3389,  1.2307, -0.2581],
         [ 0.8634, -0.3495,  0.1283,  0.6885, -0.2082],
         [ 0.3983,  0.8135,  0.5561, -0.8639, -0.3407],
         [-0.4362, -0.2393, -0.2225,  0.9875,  0.5437]],

        [[-0.3561, -1.3942,  0.8677,  0.5003,  2.9590],
         [ 2.0794,  0.3469, -0.6721,  0.2562, -0.7177],
         [-0.1500,  0.0886,  0.1107, -0.6480,  0.4077],
         [-1.2144,  2.0945, -0.5742, -0.4390,  0.0485],
         [ 1.2790, -0.1566, -1.0125,  0.6012,  0.3509]]])

In [30]:
batch_t = torch.randn(2, 3, 5, 5)

In [36]:
# RGBの平均を取って、grayに変換する(重みは考慮しない)
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [42]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [46]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [47]:
img_gray_weighted_fancy = torch.einsum("...chw,c->...hw", img_t, weights)
batch_gray_weighted_fancy = torch.einsum("...chw,c->...hw", batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [48]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named

C:\Users\ryotu\AppData\Local\Temp\ipykernel_20792\2918111397.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1463.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [49]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [51]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [52]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

名前付け機能は実験的な機能であり、本書ではこれ以降登場しない。

## 3.5 テンソルの要素の形

ニューラルネットワークで行われる計算は一般的に32ビットの浮動小数点精度で実行される。
本書ではfloat32とint64を扱う。<br>
torch.float32<br>
torch.int64

## 3.9 テンソルをGPU上で扱う方法

In [53]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")

In [54]:
points_cpu = points_gpu.cpu()

## 3.10 NumPyとの相互運用性

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [58]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])